"""Agregar audio a anuncios

Revision ID: 00466824ff2e
Revises: 3013d40b0354
Create Date: 2026-01-28 18:51:04.413224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00466824ff2e'
down_revision = '3013d40b0354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncio', schema=None) as batch_op:
        batch_op.drop_column('audio')

    # ### end Alembic commands ###
