"""ticket tramite fecha y prioridad

Revision ID: 199fe44f561c
Revises: 05dbe923af5e
Create Date: 2026-01-08 19:46:59.261967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199fe44f561c'
down_revision = '05dbe923af5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_tramite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_tramite', schema=None) as batch_op:
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###
