"""eliminacion suplentes

Revision ID: 321fd4ebbdf5
Revises: b09d8af49b1f
Create Date: 2026-01-06 11:56:53.479891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321fd4ebbdf5'
down_revision = 'b09d8af49b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplente', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['id_usuario'], ['id_usuario'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'usuario', ['id_suplente_usuario'], ['id_usuario'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('1'), 'usuario', ['id_suplente_usuario'], ['id_usuario'])
        batch_op.create_foreign_key(batch_op.f('2'), 'usuario', ['id_usuario'], ['id_usuario'])

    # ### end Alembic commands ###
