"""usuario ventanilla

Revision ID: 523a40237c7f
Revises: 9acdcfa7d6b4
Create Date: 2025-12-21 18:28:20.365760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523a40237c7f'
down_revision = '9acdcfa7d6b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventanilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['id_usuario'])
        batch_op.create_foreign_key(None, 'usuario', ['id_usuario'], ['id_usuario'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventanilla', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###
