"""init

Revision ID: 5c4fca51a530
Revises: 
Create Date: 2026-02-06 17:36:34.908299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4fca51a530'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anuncio',
    sa.Column('id_anuncio', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('enlace', sa.String(length=500), nullable=False),
    sa.Column('audio', sa.String(length=500), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_anuncio')
    )
    op.create_table('area',
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_area'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ticket',
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('turno', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_ticket')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ap_paterno', sa.String(length=45), nullable=False),
    sa.Column('ap_materno', sa.String(length=45), nullable=True),
    sa.Column('role', sa.String(length=45), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id_area'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ventanilla',
    sa.Column('id_ventanilla', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('id_area', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_area'], ['area.id_area'], ),
    sa.PrimaryKeyConstraint('id_ventanilla'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suplente',
    sa.Column('id_suplente', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_suplente_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_suplente_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_suplente')
    )
    op.create_table('tramite',
    sa.Column('id_tramite', sa.Integer(), nullable=False),
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id_ventanilla', sa.Integer(), nullable=True),
    sa.Column('requerimientos', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_area'], ['area.id_area'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_ventanilla'], ['ventanilla.id_ventanilla'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_tramite')
    )
    op.create_table('asignacion',
    sa.Column('id_asignacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_tramite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tramite'], ['tramite.id_tramite'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_asignacion')
    )
    op.create_table('ticket_tramite',
    sa.Column('id_ticket_tramite', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('id_tramite', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_ticket'], ['ticket.id_ticket'], ),
    sa.ForeignKeyConstraint(['id_tramite'], ['tramite.id_tramite'], ),
    sa.PrimaryKeyConstraint('id_ticket_tramite')
    )
    op.create_table('atencion',
    sa.Column('id_atencion', sa.Integer(), nullable=False),
    sa.Column('id_ticket_tramite', sa.Integer(), nullable=False),
    sa.Column('id_ventanilla', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('descripcion_estado', sa.String(length=100), nullable=True),
    sa.Column('hora_inicio', sa.DateTime(), nullable=True),
    sa.Column('hora_fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_ticket_tramite'], ['ticket_tramite.id_ticket_tramite'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_ventanilla'], ['ventanilla.id_ventanilla'], ),
    sa.PrimaryKeyConstraint('id_atencion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atencion')
    op.drop_table('ticket_tramite')
    op.drop_table('asignacion')
    op.drop_table('tramite')
    op.drop_table('suplente')
    op.drop_table('ventanilla')
    op.drop_table('usuario')
    op.drop_table('ticket')
    op.drop_table('area')
    op.drop_table('anuncio')
    # ### end Alembic commands ###
