"""tamaño descripcion atencion

Revision ID: 622462f8be27
Revises: 94d6d70239b5
Create Date: 2026-01-22 19:46:00.226442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '622462f8be27'
down_revision = '94d6d70239b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atencion', schema=None) as batch_op:
        batch_op.alter_column('descripcion_estado',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atencion', schema=None) as batch_op:
        batch_op.alter_column('descripcion_estado',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)

    # ### end Alembic commands ###
