"""atencion tramite

Revision ID: 84c4487b6512
Revises: 5c4fca51a530
Create Date: 2026-02-16 12:21:03.692324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c4487b6512'
down_revision = '5c4fca51a530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atencion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_tramite', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tramite', ['id_tramite'], ['id_tramite'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atencion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_tramite')

    # ### end Alembic commands ###
