"""correcciones ventanilla y suplente

Revision ID: 870fe8fb134e
Revises: 
Create Date: 2026-01-13 13:23:16.266996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '870fe8fb134e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplente', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('tramite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_ventanilla', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ventanilla', ['id_ventanilla'], ['id_ventanilla'])

    with op.batch_alter_table('ventanilla', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('id_usuario'))
        batch_op.drop_constraint(batch_op.f('2'), type_='foreignkey')
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventanilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('2'), 'usuario', ['id_usuario'], ['id_usuario'])
        batch_op.create_index(batch_op.f('id_usuario'), ['id_usuario'], unique=True)

    with op.batch_alter_table('tramite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_ventanilla')

    with op.batch_alter_table('suplente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
