"""requerimientos tramite

Revision ID: 94d6d70239b5
Revises: 9b9961abf428
Create Date: 2026-01-21 17:49:36.580549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d6d70239b5'
down_revision = '9b9961abf428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tramite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requerimientos', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tramite', schema=None) as batch_op:
        batch_op.drop_column('requerimientos')

    # ### end Alembic commands ###
