"""asignacion ondelete

Revision ID: 9ad2be461707
Revises: 0cdda99696d8
Create Date: 2026-01-19 18:18:09.797719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad2be461707'
down_revision = '0cdda99696d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asignacion', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('asignacion_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('asignacion_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tramite', ['id_tramite'], ['id_tramite'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'usuario', ['id_usuario'], ['id_usuario'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asignacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('asignacion_ibfk_1'), 'tramite', ['id_tramite'], ['id_tramite'])
        batch_op.create_foreign_key(batch_op.f('asignacion_ibfk_2'), 'usuario', ['id_usuario'], ['id_usuario'])

    # ### end Alembic commands ###
