"""nombre usuario

Revision ID: abede16ecfbd
Revises: 523a40237c7f
Create Date: 2025-12-22 13:02:09.724065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abede16ecfbd'
down_revision = '523a40237c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('ap_paterno', sa.String(length=45), nullable=False))
        batch_op.add_column(sa.Column('ap_materno', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('ap_materno')
        batch_op.drop_column('ap_paterno')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
