"""correcciones ventanilla y suplente

Revision ID: ac3695107434
Revises: 870fe8fb134e
Create Date: 2026-01-13 13:24:03.098916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac3695107434'
down_revision = '870fe8fb134e'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('ventanilla', schema=None) as batch_op:
        batch_op.drop_constraint(
            '2',
            type_='foreignkey'
        )
        batch_op.drop_index('id_usuario')
        batch_op.drop_column('id_usuario')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventanilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('2'), 'usuario', ['id_usuario'], ['id_usuario'])
        batch_op.create_index(batch_op.f('id_usuario'), ['id_usuario'], unique=True)

    # ### end Alembic commands ###
