"""anuncios

Revision ID: cce2c8bfcb8c
Revises: 622462f8be27
Create Date: 2026-01-28 13:35:46.142335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce2c8bfcb8c'
down_revision = '622462f8be27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anuncio',
    sa.Column('id_anuncio', sa.Integer(), nullable=False),
    sa.Column('enlace', sa.String(length=255), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_anuncio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anuncio')
    # ### end Alembic commands ###
