"""configuracion atencion ondelete

Revision ID: d3f6642a9c9e
Revises: 9ad2be461707
Create Date: 2026-01-19 18:22:11.824503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f6642a9c9e'
down_revision = '9ad2be461707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tramite', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tramite_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tramite_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ventanilla', ['id_ventanilla'], ['id_ventanilla'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'area', ['id_area'], ['id_area'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tramite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tramite_ibfk_2'), 'ventanilla', ['id_ventanilla'], ['id_ventanilla'])
        batch_op.create_foreign_key(batch_op.f('tramite_ibfk_1'), 'area', ['id_area'], ['id_area'])

    # ### end Alembic commands ###
