"""soft delete tramite

Revision ID: d73024a5764e
Revises: fb26cd2d84db
Create Date: 2026-01-19 18:37:20.424147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73024a5764e'
down_revision = 'fb26cd2d84db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tramite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tramite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
