"""area usuario

Revision ID: de7344a6fc48
Revises: 00466824ff2e
Create Date: 2026-01-30 11:21:40.280339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7344a6fc48'
down_revision = '00466824ff2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'area', ['area_id'], ['id_area'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('area_id')

    # ### end Alembic commands ###
