"""ajuste anuncio

Revision ID: eb585c96156c
Revises: cce2c8bfcb8c
Create Date: 2026-01-28 14:14:23.026757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb585c96156c'
down_revision = 'cce2c8bfcb8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=False))
        batch_op.alter_column('enlace',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncio', schema=None) as batch_op:
        batch_op.alter_column('enlace',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
